APP:
  NAME: go_simpleweibo
  RUNMODE: debug # 模式: debug, release, test
  Addr: :8889 # 端口
  URL: http://localhost:8889 # 网站 url，内部跳转时会用到该项
  KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
  ENABLE_CSRF: false # 是否开启 csrf

DB:
  CONNECTION: mysql
  HOST: 192.168.164.168 #127.0.0.1
  PORT: 3306
  DATABASE: go_simpleweibo
  USERNAME: wxl
  PASSWORD: 111111Aa

MAIL:
  MAIL_DRIVER: log # smtp or log (smtp: 使用支持 ESMTP 的 SMTP 服务器发送邮件，log: 适用于调试，会将邮件内容写入 log 中)
  MAIL_HOST: smtp.163.com # 邮箱的 SMTP 服务器地址
  MAIL_PORT: 143 # 邮箱的 SMTP 服务器端口
  MAIL_USERNAME: starichat@163.com
  MAIL_PASSWORD: starichat163 # 授权码或密码
  MAIL_FROM_NAME: go_simpleweibo # 用来作为邮件的发送者名称
